version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: cimbirodalom_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data